name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Lint
        run: |
          pip install flake8
          flake8 --ignore E501,E402 src/